### PR TITLE
Use upper bounded wildcard for interface methods returning list #145

### PR DESCRIPTION
**Pull request by kobylynskyi**

### CODE REVIEW

**Comment by kobylynskyi** [comment]
@joffrey-bion could you please review this PR when you have time? Thanks.

**Comment by joffrey-bion** [comment]
Hi @kobylynskyi , sorry for the delay in review, I actually didn't have much time to take a look these days, and then I forgot about it.

This looks very nice!

I'm just wondering whether some of test files were added on purpose or not. The `expected-classes` make sense, but I'm not sure you meant to check in the ones like `src/test/java/com/kobylynskyi/graphql/codegen/model/Foo1.java.txt`. Is this intended?

**Comment by kobylynskyi** [comment]
@joffrey-bion, thanks for your review!
Yes, it is intended. There is a test which generates classes with such names (copies from the corresponding issue

**Comment by joffrey-bion** [comment]
@kobylynskyi but if it's generated then it shouldn't be checked in the repo, should it?

**Comment by kobylynskyi** [comment]
@joffrey-bion, I've removed the classes you mentioned. Thank you for pointing this out!

**Pull request merged**
