### PR TITLE
Add annotations to JavaBean getters

### PR DESCRIPTION
**Pull request by ludovicc**
### Description

Add nonnull and other annotations to the getter method in addition to the field declaration. Some Java Bean introspection tools can only use annotations declared on the getter/setter methods, not on the private fields, so we need to repeat the annotation that was placed on the field on the getter as well to get full introspection with annotations.

---

Changes were made to:
- [x] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

### CODE REVIEW

**Comment by kobylynskyi** [comment]
@ludovicc looks good. but could you please change the target branch to **develop**?

**Comment by kobylynskyi** [comment]
@ludovicc can you please fix the build?

**Comment by JamesPeters98** [comment]
Any chance you can fix the build @ludovicc? This would be really useful for me too

**Comment by JamesPeters98** [comment]
Actually, I just realised I need this for Setters as well

**Pull request closed without merging**
