### PR TITLE
fix: Updated dependencies to resolve security vulnerabilities

### PR DESCRIPTION
**Pull request by upendrao**
---

### Description

Related to #1045 

Updated following dependencies to resolve security vulnerabilities
- `com.graphql-java:graphql-java`
- `com.fasterxml.jackson.core:jackson-databind`
Updated unit tests to be able to parse test schemas with more tokens than the default size(15000) 

---

Changes were made to:
- [ ] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin
- [x] Dependencies

### CODE REVIEW

**Review by kobylynskyi — APPROVED** [review]

**Comment by kobylynskyi** [comment]
Thanks @upendrao for the contribution!

**Comment by upendrao** [comment]
@kobylynskyi I'm looking at the failure and shall submit a PR on that.

**Comment by upendrao** [comment]
Hi @kobylynskyi ! Can I ask you a question here?
I have bunch of graphql [schemas](https://github.com/acryldata/datahub/tree/master/datahub-graphql-core/src/main/resources) from DataHub on top of which I want to write my own custom queries as we run from a GraphQL end point. How can I use this plugin to generate code for custom queries. 
For example I tried to add an additional graphql file in the schemas folder for the plugin but could not see any code generated for my custom query. Any leads?

**Comment by upendrao** [comment]
Hi,
If I use 'extend type Query {' then I think I need to implement that query
on my own as it wont exist on GraphQL server.
For example I have a query as follows then I want to generate Java/Kotlin
code for that query so that I can easily deserialize the response into it.
query {
listDomains(
input: {}
) {
start
count
total
domains {
urn
properties {
name
}
}
}
}
The types defined in the base schema (ex: Domain here) have a mix of
nullable and non-nullable fields.
But in a query projection we (want to)list only a subset of the fields of a
specific type.
I am experiencing a challenge while deserializing such types when the
projection does not include a non-nullable field.
Is there any fix for this on the json codec?

Best Regards,
Upendra

**Pull request merged**
