### PR TITLE
Release 5.1.0

### PR DESCRIPTION
**Pull request by kobylynskyi**
* Ability to disable generation of the all$ method in projections #645
* Generate jackson type id resolver annotation #637
* Add directive support for types #660 #665
* GraphQL serialization of java.util.Map #668 #669

### CODE REVIEW

**Comment by jxnu-liguobin** [comment]
image
have a bug, NPE

**Comment by jxnu-liguobin** [comment]
> > image
> > have a bug, NPE
> 
> Could the definition ever be null? I understand why sonar thinks it (because of the conditional) but will it ever happen?

Maybe because there is a check on the front, sonar thinks that the following also needs to be checked

**Comment by kobylynskyi** [comment]
Agree with @jxnu-liguobin 
If the variable is null-checked, then all subsequent usages of this variable are considered nullable.
So we can either remove this null-check (if `extendedDefinition` is always non-null), or add null-check at all usages of `extendedDefinition`

**Comment by robbertnoordzij** [comment]
> Agree with @jxnu-liguobin
> If the variable is null-checked, then all subsequent usages of this variable are considered nullable.
> So we can either remove this null-check (if `extendedDefinition` is always non-null), or add null-check at all usages of `extendedDefinition`

Not sure if someone was already fixing it, but I created an PR: https://github.com/kobylynskyi/graphql-java-codegen/pull/666

**Comment by robbertnoordzij** [comment]
I noticed checkstyle does not run with gradle and not on the PR's. I see in this branch it found 2 issues: 

- Whitespace
- Order of the getAnnotations method

I created an PR to fix them both: https://github.com/kobylynskyi/graphql-java-codegen/pull/667.

Hope this helps.

**Pull request merged**
