### PR TITLE
use objectMapperForSerialization for kotlin type classes

### PR DESCRIPTION
**Pull request by jay3047**
---

### Description

Related to #995 

---

Changes were made to:
- [ ] Codegen library - Java
- [x] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

### CODE REVIEW

**Comment by jay3047** [comment]
Not sure why sonar is failing , @jxnu-liguobin can you please help.

**Comment by jxnu-liguobin** [comment]
> sonar

Usually we do not need to care about soar.

**Comment by jay3047** [comment]
> > sonar
> 
> Usually we do not need to care about soar.

Okay , in that case can you please review and merge if changes looks ok.

**Review by jxnu-liguobin — APPROVED** [review]

**Comment by jay3047** [comment]
@kobylynskyi Can you please review and merge

**Comment by jxnu-liguobin** [comment]
> @kobylynskyi Can you please review and merge

He's probably still sleeping 😄 .

**Pull request merged**
