### PR TITLE
Do not skip "...on" in all$ methods for union and interface projections

### PR DESCRIPTION
**Pull request by sdaurea**
---

### Description

Related to #1375

---

Changes were made to:
- [x] Codegen library - Java
- [x] Codegen library - Kotlin
- [x] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

### CODE REVIEW

**Comment by jxnu-liguobin** [comment]
When you open it, does it mean you are in need of it? This is great. Can you test if it really meets the requirements? Thank you!

Because I skipped it directly to avoid testing the union.

**Comment by alaa-nassef** [comment]
> When you open it, does it mean you are in need of it? This is great. Can you test if it really meets the requirements? (Test its results at runtime ) Thank you!
> 
> Because I skipped it directly to avoid testing the union.

@jxnu-liguobin to answer your first question, yes, we do need this in the project we're working on and it is currently kind of a blocker for us. As for testing results at runtime, we were planning to do this, but we have to publish our own version first and use it instead, which would need some more time

**Comment by kobylynskyi** [comment]
@alaa-nassef looks good!. Thanks for the contribution!

**Comment by derwild** [comment]
I'm not sure about your release schedule, but can you already say, when the 5.9.0 maven plugin will be released?

**Comment by kobylynskyi** [comment]
@derwild targeting this week.

**Pull request merged**
