### PR TITLE
#1297 Allow to exclude fields from generated GraphQL objects

### PR DESCRIPTION
**Pull request by sabirove**
---

### Description

Related to #1297 

---

Changes were made to:
- [ ] Codegen library - Java
- [ ] Codegen library - Kotlin
- [ ] Codegen library - Scala
- [ ] Maven plugin
- [ ] Gradle plugin
- [ ] SBT plugin

### CODE REVIEW

**Comment by sabirove** [comment]
Hey @kobylynskyi , @jxnu-liguobin , the build seems to be broken.

```
* What went wrong:
A problem occurred configuring root project 'graphql-java-codegen'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.3225.
     Required by:
         project : > org.sonarqube:org.sonarqube.gradle.plugin:4.3.0.3225
      > No matching variant of org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.3225 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.2' but:
          - Variant 'apiElements' capability org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.3225 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'javadocElements' capability org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.3[22](https://github.com/kobylynskyi/graphql-java-codegen/actions/runs/5781556112/job/15666845991?pr=1299#step:7:23)5 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'runtimeElements' capability org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.32[25](https://github.com/kobylynskyi/graphql-java-codegen/actions/runs/5781556112/job/15666845991?pr=1299#step:7:26) declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'sourcesElements' capability org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.3.0.3225 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
```

Any ideas how to fix this?

**Comment by jxnu-liguobin** [comment]
My PR is the same, I'm not sure what happened 🥲

**Comment by kobylynskyi** [comment]
@sabirove, looks good. But please add your new property to:
https://github.com/kobylynskyi/graphql-java-codegen/blob/37ffc689a6c8d67744ebe65c825261e790d246e8/src/main/java/com/kobylynskyi/graphql/codegen/model/MappingConfig.java#L130
(and `MappingConfigTest` as well)

**Review by kobylynskyi — APPROVED** [review]
Thanks for the contribution. Will include this change in the next release. Stay tuned.

**Comment by yeikel** [comment]
@kobylynskyi When is the release planned?

**Pull request merged**
