### PR TITLE
Adding the option to generate an equals and hashcode method

### PR DESCRIPTION
**Pull request by a-stewart**

### CODE REVIEW

**Comment by kobylynskyi** [comment]
@a-stewart , thanks for contributing. Will release it today as part of **1.2.3**

**Comment by kobylynskyi** [comment]
@a-stewart I see 3 errors after generating the model:
Screenshot 2019-09-24 10 33 38

**Comment by kobylynskyi** [comment]
@a-stewart, fixed above errors

**Comment by a-stewart** [comment]
Thanks, sorry was in a bit of rush yesterday trying to get it completed before heading to the airport.

**Pull request merged**
